- name: Install and start Nginx
  hosts: node
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.package:  # This is the module that will be used to install Nginx
      name: nginx
      state: present
  - name: Start Nginx
    ansible.builtin.service:  # This is the module that will be used to start Nginx
      name: nginx
      state: started  
      enabled: yes