- name: "Variables in Ansible"
  hosts: local
  connection: local # Use local connection to run the playbook on the control machine
  vars:
    NAME: "Ram"
    COURSE: "Ansible"
  tasks:
  - name: "Print the Name and Course Details"
    ansible.builtin.debug:  # Use the debug module to print the variables
      msg: "Name is : {{ NAME }} and Course is : {{ COURSE }}"
      
  