- name: Conditions
  hosts: local
  connection: local
  vars_prompt:
    - name: "number"
      prompt: "Enter a number to check if it's even or odd"
      private: no
  tasks:
    - name: Check if a number is even or odd
      ansible.builtin.debug:
        msg: "Given Number {{ number }} is Even"
      when: number | int % 2 == 0