- name: functions
  hosts: localhost
  connection: local
  vars:
    tech: Ansible, Python, Linux, DevOps 
    # Dictinoary variable
    tags:
      Application: Web
      Environment: Production
    # List variable 
    ListTags:
      - key: Application
        value: Web
      - key: Environment
        value: Production
  tasks:
    - name: Default variable
      ansible.builtin.debug:
        msg: "Hello, {{ name | default('World') }}"
        # The default filter is used to provide a default value for a variable if it is not defined. In this case, if the variable 'name' is not defined, it will use 'World' as the default value. So if you run this playbook without defining the 'name' variable, it will output "Hello, World". If you define the 'name' variable with a value, it will output "Hello, <value of name>".

    - name: Split the string into a list
      ansible.builtin.debug:
        msg: "Technologies are: {{ tech | split(', ') }}" # The split filter is used to split a string into a list based on a specified delimiter.

    - name: Split the Disctionary into a list
      ansible.builtin.debug:
        msg: "Tags are : {{ tags | dict2items }}" # The dict2items filter is used to convert a dictionary into a list of dictionaries,

    - name: Split the List of Disctionary into a map
      ansible.builtin.debug:
        msg: "List of Tags are: {{ ListTags | items2dict(key_name='key', value_name='value') }}" # The items2dict filter is used to convert a list of dictionaries into a single dictionary.

    - name: Read yaml and take it into variable
      ansible.builtin.set_fact:  # The set_fact module is used to set new variables.
        student_info: "{{ lookup('file', 'student.yaml') | from_yaml }}" # The lookup function is used to read the contents of a file, and the from_yaml filter is used to parse the YAML content into a Python dictionary.

    - name: Convert the yaml data into json format
      ansible.builtin.debug:
        msg: "Student Info in JSON format: {{ student_info | to_json }}" # The to_json filter is used to convert a Python dictionary into a JSON string.

    - name: Save JSON to file
      ansible.builtin.copy:
        dest: ./student.json
        content: "{{ student_info | to_nice_json }}" # The content parameter is used to specify the content of the file being created or modified. In this case, it is set to the JSON representation of the student_info variable, which is generated using the to_json filter.

    - name: Grep for root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: command_output
    
    - name: Print the command output
      ansible.builtin.debug:
        msg: "Command output: {{ command_output.stdout }}" # The stdout attribute of the registered variable contains the standard output of the command that was executed. In this case, it will contain the lines from the /etc/passwd file that contain the word "root".

    - name: Redirect the command output
      ansible.builtin.commnd: ls -lrt > /tmp/output.txt # The command module is used to execute a command on the remote host. In this case, it is executing the ls -lrt command and redirecting its output to a file located at /tmp/output.txt on the remote host. The > operator is used for output redirection in shell commands, which means that the output of the ls -lrt command will be written to the specified file instead of being displayed in the terminal.
      register: redirected_output

    - name: Print the redirected command output
      ansible.builtin.debug:
        msg: "Redirected command output: {{ redirected_output }}" # The stdout attribute of the registered variable will contain the output of the command that was executed. However, since the output is being redirected to a file, the stdout will likely be empty or contain only a message indicating that the command was executed successfully. To see the actual output of the command, you would need to read the contents of the /tmp/output.txt file on the remote host.
